import type { NextPage } from "next";
import Head from "next/head";
import { useState, useEffect } from "react";
import { useSession, signIn, signOut } from "next-auth/react";
import { useRouter } from "next/router";

const Home: NextPage = () => {
  // const [email, setEmail] = useState("");
  // console.log("email", email);
  // const handleRegister = async () => {
  //   console.log("email", email);
  //   try {
  //     // Perform sign in
  //     const { error } = await signIn("email", {
  //       redirect: false,
  //       callbackUrl: window.location.href,
  //       email,
  //     });
  //     // Something went wrong
  //     if (error) {
  //       throw new Error(error);
  //     }
  //   } catch (err) {
  //     alert("error");
  //   } finally {
  //     console.log("done");
  //   }
  // };
  const router = useRouter();
  const isAuthenticated = false;
  useEffect(() => {
    if (!isAuthenticated) {
      router.push("/authentication");
    } else router.push("/");
  });

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <input
          type="email"
          placeholder="Email"
          onChange={(e) => setEmail(e.target.value)}
        />
        <button
          onClick={(e) => {
            e.preventDefault();
            handleRegister();
          }}
        >
          Register
        </button>
      </main>
    </div>
  );
};

export default Home;
